port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

proxies:

proxy-groups:
  - name: 节点选择
    type: select
    proxies:
      - 自动选择
      - 香港节点
      - 日本节点
      - 新加坡节点
      - 其他节点     
      - 负载均衡
      - 失败切换
      - DIRECT
  - name: 香港节点
    type: select
    proxies:
  - name: 日本节点
    type: select
    proxies:
  - name: 新加坡节点
    type: select
    proxies:
  - name: 其他节点
    type: select
    proxies:
  - name: 自动选择
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    tolerance: 50
    proxies:
  - name: 负载均衡
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
  - name: 失败切换
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
  - name: 谷歌服务
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 日本节点
      - 新加坡节点
      - DIRECT

rule-providers: # rule-providers from Logyalsoldier/clash-rules and LM-Firefly/Rules
  Google:
    type: http
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt
    path: ./ruleset/TopFreeProxies/google.yaml
    interval: 86400

rules:
  - RULE-SET,Google,谷歌服务
  - MATCH,节点选择
